version: "3.9"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 projftth.wsgi:application
    volumes:
      - ./:/code
      - ./static:/static
    ports:
      - 8001:8001
    restart: always
  proxy:
    build: ./nginx
    volumes:
      - ./:/app
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
