# Generated by Django 3.2.6 on 2022-05-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, default='Escreva sua descrição aqui', null=True, verbose_name='Descrição')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Instalação')),
                ('qtdPortas', models.CharField(blank=True, choices=[('8', '8'), ('16', '16'), ('128', '128')], default='8', max_length=100, null=True, verbose_name='Quantidade de Portas')),
                ('nomeCto', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nome da CTO')),
                ('sinalCto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinal da CTO')),
            ],
            options={
                'verbose_name': 'CTO',
                'verbose_name_plural': 'CTOs',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='ModeloOlt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeModeloOlt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('quantPortas', models.CharField(blank=True, choices=[('4', '4'), ('8', '8'), ('16', '16')], max_length=100, null=True, verbose_name='Porta Pon')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fabricante')),
            ],
            options={
                'verbose_name': 'ModeloOlt',
                'verbose_name_plural': 'ModelosOlt',
            },
        ),
        migrations.CreateModel(
            name='ModeloOnu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeModeloOnu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('quantPortasLans', models.CharField(blank=True, default='1', max_length=100, null=True, verbose_name='Quantidade de portas')),
                ('wifi', models.CharField(blank=True, choices=[('s', 's'), ('n', 'n')], default='n', max_length=100, null=True, verbose_name='Tem wifi?')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fabricante')),
            ],
            options={
                'verbose_name': 'ModeloOnu',
                'verbose_name_plural': 'ModelosOnu',
            },
        ),
        migrations.CreateModel(
            name='Modo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeModo', models.CharField(blank=True, choices=[('bridge', 'bridge'), ('router', 'router'), ('outro', 'outro')], max_length=100, null=True, verbose_name='Modo')),
            ],
            options={
                'verbose_name': 'Modo',
                'verbose_name_plural': 'Modos',
            },
        ),
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, default='Escreva sua descrição aqui', null=True, verbose_name='Descrição')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Instalação')),
                ('nomeOlt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido da Olt')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço IP')),
                ('login', models.CharField(blank=True, default='admin', max_length=100, null=True, verbose_name='Login')),
                ('senha', models.CharField(blank=True, default='parks', max_length=100, null=True, verbose_name='Senha')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modeloolt')),
            ],
            options={
                'verbose_name': 'Olt',
                'verbose_name_plural': 'OLTs',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePlano', models.CharField(max_length=100, verbose_name='Plano')),
                ('down', models.CharField(max_length=100, verbose_name='Down')),
                ('up', models.CharField(max_length=100, verbose_name='Up')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Pon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pon/Área')),
                ('sinalPon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinal em dBm')),
                ('portaPon', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=100, null=True, verbose_name='Porta Pon')),
                ('olt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.olt')),
            ],
            options={
                'verbose_name': 'PON',
                'verbose_name_plural': 'PONs',
            },
        ),
        migrations.CreateModel(
            name='PortasCto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPorta', models.CharField(max_length=100)),
                ('statusPorta', models.CharField(blank=True, choices=[('ocupada', 'ocupada'), ('livre', 'livre')], default='livre', max_length=100, null=True, verbose_name='Status Da Porta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('desprovisionar', models.TextField(blank=True, null=True, verbose_name='Desprovisionar')),
                ('cto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cto')),
            ],
            options={
                'verbose_name': 'Porta',
                'verbose_name_plural': 'Portas',
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeValn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vlan')),
                ('vlanID', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Vlan')),
                ('modo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modo')),
                ('pon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pon')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
            },
        ),
        migrations.CreateModel(
            name='Provisionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('onu', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('modo', models.CharField(blank=True, choices=[('bridge', 'bridge'), ('router', 'router'), ('outro', 'outro')], default='bridge', max_length=100, null=True, verbose_name='Modo')),
                ('sinal', models.CharField(blank=True, max_length=100, null=True)),
                ('dataInstalacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Instalação')),
                ('cto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cto')),
                ('olt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.olt')),
                ('pon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pon')),
                ('portaCto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.portascto')),
                ('vlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vlan')),
            ],
            options={
                'verbose_name': 'Provisionamento',
                'verbose_name_plural': 'Provisionamentos',
            },
        ),
        migrations.CreateModel(
            name='Onu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número do Serial')),
                ('modeloOnu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modeloonu')),
            ],
            options={
                'verbose_name': 'ONU',
                'verbose_name_plural': 'ONUs',
            },
        ),
        migrations.AddField(
            model_name='cto',
            name='pon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pon'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, default='Escreva sua descrição aqui', null=True, verbose_name='Descrição')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Instalação')),
                ('nomeCliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('nomeUser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário')),
                ('emailUser', models.EmailField(blank=True, default='cliente@portalcrtelecom.com.br', max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='cr', max_length=100, null=True, verbose_name='Senha')),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plano')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
